replicaCount: 2

image:
  repository: eslamanwar/zar
  tag: v1.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 80

livenessProbe:
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3
