name: Helm Chart Test on KIND

on:
  push:
    paths:
      - 'devops/k8s/chart/**'
    branches:
      - main
  pull_request:
    paths:
      - 'devops/k8s/chart/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up KIND cluster
      uses: engineerd/setup-kind@v0.11.1
      with:
        version: v0.20.0

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - name: Load Helm chart
      run: helm lint ./devops/k8s/chart

    - name: Install Helm chart on KIND
      run: helm install test-release ./devops/k8s/chart

    - name: Wait for Deployment to be ready
      run: |
        kubectl rollout status deployment/your-app --timeout=2m

    - name: Run tests
      run: |
        kubectl get pods

    - name: Uninstall Helm release
      if: always()
      run: helm uninstall test-release
